base16:
  filename: theme/{{ scheme-system }}-{{ scheme-slug }}/theme.txt
  supported-systems: [base16]

base24:
  filename: theme/{{ scheme-system }}-{{ scheme-slug }}/theme.txt
  supported-systems: [base24]

renamer-base16:
  filename: theme/{{ scheme-system }}-{{ scheme-slug }}/renamer.ps1
  supported-systems: [base16,base24]

tinted8:
  filename: theme/{{ scheme.system }}-{{ scheme.slug }}/theme.txt
  supported-systems: [tinted8]
  supports:
    tinted8-builder: "~0.2.0"
    tinted8-styling: "~0.2.0"

renamer-tinted8:
  filename: theme/{{ scheme.system }}-{{ scheme.slug }}/renamer.ps1
  supported-systems: [tinted8]
  supports:
    tinted8-builder: "~0.2.0"
    tinted8-styling: "~0.2.0"
